# Generated by Django 3.2.7 on 2021-10-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0003_alter_variation_product'),
        ('cart', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='my_store.Variation'),
        ),
    ]
